### PR TITLE
Add exhaustive sampling and rename the default export to `consecutiveUniqueRandom`

### LINKED ISSUE #9: Add option to use all number from the range before repeating any numbers
This can be useful, for example, for a music shuffle functionality. It should also ensure numbers across boundaries don't overlap. This would also be useful for slideshows to ensure the images don't show like "image A, image F, image A, …".

### PR DESCRIPTION
**Pull request by Richienb**
rfc

Fixes #9

### CODE REVIEW

**Comment by sindresorhus** [comment]
What's the benefit of this over an option? Just curious about your thinking. I haven't made up my mind yet either way.

**Comment by Richienb** [comment]
By separating them, we force users to make a conscious decision about which type of randomness they are looking for. If we were to just make it option, the user might start with the defaults, realize that its not what they wanted, and if lucky, find the option they need to change.

**Comment by sindresorhus** [comment]
Good point. I agree.

**Comment by Richienb** [comment]
@sindresorhus Am wondering: I can't tell whether or not you got an email from me marking it as ready to review and you're just busy with other things, or if pinging you is the only alternative to waiting for it come around...

**Comment by Richienb** [comment]
Making draft because just spotted: https://github.com/sindresorhus/unique-random/pull/12#issuecomment-1237615361

**Pull request merged**
